---
- name: Configuration de la machine distante
  hosts: all
  become: yes

  tasks:
    - name: Mise à jour des packages
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Installation de Nginx
      apt:
        name:
          - nginx

    - name: Copie du fichier de configuration de Nginx
      copy:
        src: /path/to/your/nginx/site.conf
        dest: /etc/nginx/sites-available/default
      notify: Reload nginx

    - name: Activation de la configuration de Nginx
      file:
        src: /etc/nginx/sites-available/default
        dest: /etc/nginx/sites-enabled/default
        state: link
      notify: Reload nginx

  handlers:
    - name: Reload nginx
      systemd:
        name: nginx
        state: restarted
