---
- name: Deploy LEMP environment and secure server
  hosts: web_servers
  become: true

  tasks:

  - name: Update apt cache and packages
    apt:
      update_cache: yes
      cache_valid_time: 3600
    when: ansible_os_family == 'Debian'

  - name: Install required packages
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - nginx
      - mysql-server
      - php-fpm
      - php-mysql
      - php-curl
      - php-gd
      - php-mbstring
      - php-xml
      - unzip
    when: ansible_os_family == 'Debian'

  - name: Configure Nginx
    copy:
      src: nginx.conf
      dest: /etc/nginx/nginx.conf
      owner: root
      group: root
      mode: 0644
    notify: Restart Nginx

  - name: Create Nginx site configuration
    template:
      src: nginx_site.conf.j2
      dest: /etc/nginx/sites-available/default
      owner: root
      group: root
      mode: 0644
    notify: Restart Nginx

  - name: Configure PHP
    lineinfile:
      path: /etc/php/7.4/fpm/php.ini
      regexp: "^;?cgi.fix_pathinfo"
      line: "cgi.fix_pathinfo = 0"
      state: present

  - name: Configure MySQL
    mysql_user:
      name: root
      host: "{{ ansible_hostname }}"
      password: "{{ mysql_root_password }}"
      login_unix_socket: /var/run/mysqld/mysqld.sock
      state: present
      login_password: "{{ mysql_root_password }}"
    notify: Restart MySQL

  - name: Secure server
    shell: |
      sed -i "s/^PermitRootLogin./PermitRootLogin no/" /etc/ssh/sshd_config
      sed -i "s/^PasswordAuthentication./PasswordAuthentication no/" /etc/ssh/sshd_config
      systemctl reload sshd
      ufw default deny incoming
      ufw default allow outgoing
      ufw allow ssh
      ufw allow http
      ufw allow https
      ufw --force enable

  handlers:
    - name: Restart Nginx
      systemd:
        name: nginx
        state: restarted

    - name: Restart MySQL
      systemd:
        name: mysql
        state: restarted
